class Recipe {
    constructor(id, title, image, prepTime, cookTime, servings, ingredients, instructions) {
        this.id = id;
        this.title = title;
        this.prepTime = prepTime;
        this.cookTime = cookTime;
        this.servings = servings;
        this.image = image;
        this.ingredients = ingredients;
        this.instructions = instructions;
    }
}


let recipes = [
    new Recipe(
        "1",
        "Classic Vanilla Delight",
        "https://i.pinimg.com/736x/6e/91/02/6e91020d810ea213cde0898a9ff9a0f9.jpg",
        '30 mins',
        "40 mins",
        "7",
        [
            "1 ¾ cups cake flour",
            "2 teaspoons baking powder",
            "¾ teaspoon salt",
            "1 cup unsalted butter, softened",
            "2 ½ cups granulated sugar",
            "2 teaspoons pure vanilla extract",
            "4 large eggs",
            "1 cup milk",
        ],
        [
            "Preheat oven to 350°F (175°C). Grease and flour two 8-inch round cake pans.",
            "In a medium bowl, whisk together cake flour, baking powder, and salt. Set aside.",
            "In a large bowl, cream together softened butter and sugar until light and fluffy. Beat in vanilla extract.",
            "Add eggs one at a time, beating well after each addition.",
            "Alternately add the dry ingredients and milk to the wet ingredients, beginning and ending with the dry ingredients. Mix until just combined, scraping down the sides of the bowl as needed.",
            "Divide batter evenly between the prepared cake pans.",
            "Bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean. Let cakes cool in pans for 10 minutes, then transfer to a wire rack to cool completely.",
            "Once cool, frost the cake with your favorite vanilla frosting. Enjoy!",
        ]
    ),

    new Recipe(
        "2",
        "Decadent Chocolate",
        "https://i.pinimg.com/564x/11/1b/a0/111ba08583add9caf476d6cae573f43c.jpg",
        '35 mins',
        "45 mins",
        "12",
        [
            // Cake ingredients
            "1 ¾ cups all-purpose flour",
            "1 teaspoon baking soda",
            "1 teaspoon baking powder",
            "½ teaspoon salt",
            "1 cup (2 sticks) unsalted butter, softened",
            "1 ¾ cups granulated sugar",
            "3 large eggs",
            "1 teaspoon pure vanilla extract",
            "1 cup buttermilk",
            "¾ cup unsweetened cocoa powder",
            "1 cup hot coffee",
            "1 cup heavy cream",
            "12 oz semisweet chocolate chips",
        ],
        [
            "Preheat oven to 350 degrees F (175 degrees C). Grease and flour two 9-inch round cake pans.",
            "In a medium bowl, whisk together flour, baking soda, baking powder, and salt.",
            "In a large bowl, cream together butter and sugar until light and fluffy. Beat in eggs one at a time, then stir in vanilla extract.",
            "In a separate bowl, whisk together buttermilk and cocoa powder until smooth. Gradually add the buttermilk mixture to the wet ingredients, alternating with the dry ingredients. Mix until just combined.",
            "Stir in hot coffee until incorporated.",
            "Divide the batter evenly between the prepared pans. Bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean.",
            "Let the cakes cool in the pans for 10 minutes, then transfer them to a wire rack to cool completely.",
            "In a saucepan, heat heavy cream over medium heat until simmering. Remove from heat and stir in chocolate chips until melted and smooth. Let the ganache cool slightly before frosting the cake.",
            "Once the cakes are cool, place one cake layer on a serving platter. Spread a layer of chocolate ganache over the top. Top with the second cake layer and frost the entire cake with the remaining ganache. Enjoy!",
        ]
    ),
    new Recipe(
        "3",
        "Luscious Lemon Zest",
        "https://i.pinimg.com/564x/b3/3f/c1/b33fc1941d036d03a6fda2eec79dc834.jpg",
        "30 mins",
        "45 mins",
        "5",
        [
            // Cake ingredients
            "2 ½ cups cake flour",
            "2 teaspoons baking powder",
            "½ teaspoon salt",
            "1 cup (2 sticks) unsalted butter, softened",
            "1 ¾ cups granulated sugar",
            "4 large eggs",
            "1 tablespoon lemon zest",
            "½ cup fresh lemon juice",
            "1 cup buttermilk",
            "1 cup powdered sugar",
            "2-3 tablespoons fresh lemon juice",
        ],
        [
            "Preheat oven to 350 degrees F (175 degrees C). Grease and flour a 9x13 inch baking pan.",
            "In a medium bowl, whisk together flour, baking powder, and salt.",
            "In a large bowl, cream together butter and sugar until light and fluffy. Beat in eggs one at a time, then stir in lemon zest and lemon juice.",
            "Alternately add the dry ingredients and buttermilk to the wet ingredients, beginning and ending with the dry ingredients. Mix until just combined.",
            "Pour batter into the prepared pan. Bake for 50-60 minutes, or until a toothpick inserted into the center comes out clean.",
            "Let the cake cool completely in the pan before frosting or glazing.",
            "In a small bowl, whisk together powdered sugar and lemon juice until smooth. Drizzle the glaze over the cooled cake.",
        ]
    ),


    new Recipe(
        "4",
        "Velvety Red Velvet",
        "https://i.pinimg.com/564x/3e/54/cd/3e54cdf4b7e03762c6ccced98dc4580d.jpg",
        "35 mins",
        "40 mins",
        "6",
        [
            // Cake ingredients 
            "1 ¾ cups cake flour",
            "1 ½ teaspoons baking powder",
            "½ teaspoon salt",
            "1 cup (2 sticks) unsalted butter, at room temperature",
            "1 ¾ cups granulated sugar",
            "3 large eggs",
            "1 teaspoon pure vanilla extract",
            "1 cup buttermilk",
            "1 tablespoon unsweetened cocoa powder",
            "1 tablespoon red food coloring",
            "1 tablespoon white vinegar",
            "8 oz cream cheese, softened",
            "½ cup unsalted butter, softened",
            "3 cups powdered sugar",
            "1 teaspoon pure vanilla extract",
        ],
        [
            "Preheat oven to 350 degrees F (175 degrees C). Grease and flour three 8-inch round cake pans.",
            "In a medium bowl, whisk together cake flour, baking powder, and salt. Sift the dry ingredients to remove any lumps and aerate the flour for a lighter cake (optional).",
            "In a large bowl, cream together butter and sugar on medium speed for at least 3 minutes until light and fluffy. This creaming step helps incorporate air for a velvety texture.",
            "Beat in eggs one at a time, then stir in vanilla extract.",
            "In a separate small bowl, whisk together buttermilk, cocoa powder, and red food coloring. Set aside.",
            "Alternately add the dry ingredients and buttermilk mixture to the wet ingredients, beginning and ending with the dry ingredients. Mix on low speed just until combined. Overmixing can lead to a denser cake.",
            "In a small bowl, combine white vinegar and baking soda. The mixture will fizz. Quickly stir it into the cake batter. This activates the cocoa powder and buttermilk for a redder color.",
            "Divide the batter evenly between the prepared pans. Bake for 25-30 minutes, or until a toothpick inserted into the center comes out clean.",
            "Let the cakes cool in the pans for 10 minutes, then transfer them to a wire rack to cool completely.",
            "In a large bowl, cream together cream cheese and butter until light and fluffy. Beat in powdered sugar one cup at a time, until smooth and creamy. Stir in vanilla extract.",
        ]
    ),

    new Recipe(
        "5",
        "Strawberry Shortcake",
        "https://i.pinimg.com/564x/01/d1/25/01d125d645ad7af91863cc4ecc95f804.jpg",
        "20 mins",
        "45 mins",
        "8",
        [
            // Biscuit ingredients
            "2 cups all-purpose flour",
            "2 tablespoons granulated sugar",
            "2 teaspoons baking powder",
            "½ teaspoon salt",
            "½ cup (1 stick) cold unsalted butter, cubed",
            "⅓ cup milk",
            "1 large egg",
            "1 ½ pounds fresh strawberries, sliced",
            "¼ cup granulated sugar",
            "1 ½ cups heavy whipping cream, cold",
            "⅓ cup powdered sugar",
            "1 teaspoon vanilla extract",
        ],
        [
            "Preheat oven to 450 degrees F (230 degrees C). Line a baking sheet with parchment paper.",
            "In a large bowl, whisk together flour, sugar, baking powder, and salt.",
            "Using a pastry cutter or your fingertips, cut the cold butter into the dry ingredients until the mixture resembles coarse crumbs.",
            "In a separate bowl, whisk together milk and egg. Add the wet ingredients to the dry ingredients and mix until just combined. Do not overmix.",
            "Drop tablespoons of dough onto the prepared baking sheet, leaving space between them for spreading.",
            "Bake for 12-15 minutes, or until golden brown and a toothpick inserted into the center comes out clean.",
            "Let the biscuits cool on the baking sheet for a few minutes before transferring them to a wire rack to cool completely.",
            "In a medium bowl, toss the sliced strawberries with sugar and set aside for 15 minutes to allow the juices to release.",
            "In a chilled bowl, whip the heavy whipping cream, powdered sugar, and vanilla extract until stiff peaks form. Be careful not to overwhip.",
            "Once the biscuits are cool, cut them in half horizontally. Place the bottom half of a biscuit on a plate. Top with a generous amount of macerated strawberries (strawberries with their juices). Dollop whipped cream on top of the strawberries. Repeat with the remaining biscuit halves and enjoy!",
        ]
    ),

    new Recipe(
        "6",
        "Hazelnut Praline",
        "https://i.pinimg.com/564x/41/c2/1e/41c21e59b46b38fd625ba3cfafc3fea6.jpg", // Update with the actual image URL
        "25 mins",
        "35 mins",
        "9",
        [
            "1 cup (120g) whole hazelnuts",
            "1 cup (200g) granulated sugar",
            "1/4 cup (60ml) water",
            "1 ¾ cups (226g) all-purpose flour",
            "¾ cup (75g) unsweetened cocoa powder",
            "1 ½ teaspoons baking powder",
            "1 teaspoon baking soda",
            "1 teaspoon salt",
            "1 cup (2 sticks) unsalted butter, softened",
            "1 ¾ cups (350g) granulated sugar",
            "4 large eggs",
            "1 teaspoon pure vanilla extract",
            "1 cup (240ml) buttermilk",
            "1 cup (240ml) heavy cream",
            "12 oz (340g) semisweet chocolate chips",
        ],
        [
            "Preheat oven to 350°F (175°C). Spread the hazelnuts on a baking sheet and toast for 10 minutes, or until fragrant. Let cool slightly.",
            "In a medium saucepan, combine sugar and water over medium heat. Stir constantly until the sugar dissolves and the mixture comes to a simmer. Do not scrape the sides of the pan.",
            "Increase heat to medium-high and continue cooking without stirring, until the sugar turns a deep amber color. This may take 5-7 minutes.",
            "Once the sugar has caramelized, immediately remove the pan from heat and carefully add the toasted hazelnuts. Stir gently to coat the nuts with caramel. **Be careful, the caramel will be very hot!**",
            "Pour the nut mixture onto a greased baking sheet and spread into a thin layer. Let cool completely and harden. Tip: You can break the praline into smaller pieces before using it in the cake.",
            "Preheat oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.",
            "In a medium bowl, whisk together flour, cocoa powder, baking powder, baking soda, and salt.",
            "In a large bowl, cream together softened butter and sugar until light and fluffy. Beat in eggs one at a time, then stir in vanilla extract.",
            "Alternately add the dry ingredients and buttermilk to the wet ingredients, beginning and ending with the dry ingredients. Mix until just combined, be careful not to overmix.",
            " Fold in the chopped hazelnut praline (reserve some for garnish).",
            "Divide the batter evenly between the prepared cake pans. Bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean.",
            "Let the cakes cool in the pans for 10 minutes, then transfer them to a wire rack to cool completely.",
            "In a saucepan, heat heavy cream over medium heat until simmering. Remove from heat and stir in chocolate chips until melted and smooth. Let the ganache cool slightly before frosting the cake.",
            "Once the cakes are cool, place one cake layer on a serving platter. Spread a layer of chocolate ganache over the top. Top with the second cake layer.",
            "Frost the entire cake with the remaining ganache. Garnish with additional chopped hazelnut praline (optional).",
            "Enjoy your decadent Hazelnut Praline Cake!",
        ]
    ), new Recipe(
        "7",
        "Exotic Mango Passion",
        "https://i.pinimg.com/564x/87/8d/1c/878d1c7ede9711dba2db951c8d103c6b.jpg", // Update with the actual image URL
        "35 mins",
        "50 mins",
        "15",
        [
            // Yogurt Sponge Ingredients
            "100g unsalted butter, softened",
            "200g caster sugar (superfine sugar)",
            "1/2 tsp pure vanilla extract or 1/4 tsp vanilla paste",
            "3 medium eggs, separated",
            "200g natural or Greek yogurt",
            "250g plain flour (all-purpose flour)",
            "2 tsp baking powder",
            "1/2 tsp bicarbonate of soda (baking soda)",
            "1 pinch fine sea salt",
            "100g mango (diced, optional)",
            "1 large ripe mango, diced",
            "Pulp of 2 passion fruits",
            "50g granulated sugar",
            "1 tsp cornflour (cornstarch)",
            "100ml passion fruit juice",
            "50g icing sugar (powdered sugar)",
        ],
        [
            // Instructions
            "**Preheat the oven to 160°C (140°C fan / 325°F / Gas 3).** Grease and line the bottom of two 23cm (9-inch) springform pans.",
            "In a large bowl, cream together softened butter and sugar until light and fluffy. Beat in vanilla extract.",
            "Separate the eggs and add the yolks one at a time, beating well after each addition.",
            "Stir in the yogurt until just combined.",
            "In a separate bowl, whisk together flour, baking powder, baking soda, and salt.",
            "Gradually add the dry ingredients to the wet ingredients, mixing until just combined. Do not overmix.",
            "In a clean bowl, whisk the egg whites until stiff peaks form. Gently fold the egg whites into the cake batter using a spatula.",
            "Gently fold in the diced mango.",
            "Divide the batter evenly between the prepared springform pans.",
            "Bake for 12-15 minutes, or until a toothpick inserted into the center comes out clean.",
            "Let the cakes cool in the pans for a few minutes before transferring them to a wire rack to cool completely.",
            "In a small saucepan, combine diced mango, passion fruit pulp, and sugar. Heat over medium heat, stirring occasionally, until the sugar dissolves and the mixture thickens slightly.",
            "In a small bowl, mix the cornflour (cornstarch) with a little cold water to form a slurry. Add the slurry to the mango mixture and cook for another minute, stirring constantly, until the mixture thickens and becomes translucent. Remove from heat and let cool completely.",
            "In a small bowl, whisk together passion fruit juice and icing sugar until smooth and slightly thickened.",
            " Once the cakes are cool, place one cake layer on a serving plate. Spread a generous amount of the mango jam filling over the top. Top with the second cake layer.",
            "Pour the passion fruit glaze over the top of the cake, allowing it to drip down the sides. Let the glaze set slightly before slicing and serving.",
            " You can use frozen mango for the cake batter and filling, but thaw and drain any excess liquid before using.",
            "if you don't have passion fruit juice, you can substitute it with orange juice or pineapple juice.",
            "For a richer flavor, you can brush the cake layers with a simple syrup (equal parts water and sugar, simmered until sugar dissolves) before adding the filling.",
        ]
    ), new Recipe(
        "8",
        "Caramel Toffee",
        "https://i.pinimg.com/564x/c5/df/89/c5df898c3afaad563edbbf0c82bb8898.jpg", // Update with the actual image URL
        "30 mins",
        "45 mins",
        "5",
        [
            // Toffee Cake Ingredients
            "Unsalted butter, for the pan",
            "8 ounces pitted and chopped dates",
            "½ cup light rum (see substitution below)",
            "½ cup water",
            "2 cups all-purpose flour",
            "1 ½ teaspoons baking powder",
            "½ teaspoon salt",
            "½ teaspoon cinnamon",
            "¼ teaspoon baking soda",
            "½ cup unsalted butter (1 stick)",
            "1 cup dark brown sugar, packed",
            "2 eggs",
            "1 cup cream",
            "1 cup dark brown sugar, packed",
            "¼ cup unsalted butter (½ stick)",
            "¼ cup light rum ",
            "¼ cup light rum ",
        ],
        [
            "Preheat oven to 350°F (175°C). Grease a baking pan with butter.",
            "In a medium bowl, combine chopped dates, rum, and water. Let sit for at least 15 minutes to soften the dates.",
            "In a separate bowl, whisk together flour, baking powder, salt, cinnamon, and baking soda.",
            "In a large bowl, cream together softened butter and brown sugar until light and fluffy. Beat in eggs one at a time, then stir in vanilla bean paste (if using).",
            "Alternately add the dry ingredients and date mixture to the wet ingredients, beginning and ending with the dry ingredients. Mix until just combined.",
            "Pour batter into the prepared pan and bake for 75-90 minutes, or until a toothpick inserted into the center comes out clean. The top may crack slightly, but that's okay.",
            "Let the cake cool in the pan for 15 minutes before transferring it to a wire rack to cool completely.",
            "In a saucepan, heat cream over medium heat until simmering. Remove from heat and stir in brown sugar and butter until melted and smooth. Stir in rum and bring to a simmer again. Cook for 2-3 minutes, or until slightly thickened. Let cool slightly before pouring over the cake.",
            "Once the cake is cool, spoon the caramel sauce over the top. Enjoy!",
        ]
    ),
    new Recipe(
        "9",
        "Coconut Cream Paradise",
        "https://i.pinimg.com/564x/58/dd/71/58dd718b410d459d23539d51171fb82d.jpg", // Update with the actual image URL
        "30 mins",
        "45 mins",
        "5",
        [
            // Cake ingredients
            "1 ¾ cups all-purpose flour",
            "1 teaspoon baking soda",
            "½ teaspoon salt",
            "1 cup (2 sticks) unsalted butter, softened",
            "1 ½ cups granulated sugar",
            "2 large eggs",
            "1 teaspoon pure vanilla extract",
            "1 cup buttermilk",
            "1 tablespoon cocoa powder",
            "1 tablespoon red food coloring",
            "1 tablespoon white vinegar",
            "8 oz cream cheese, softened",
            "½ cup unsalted butter, softened",
            "3 cups powdered sugar",
            "1 teaspoon pure vanilla extract",
        ],
        [
            "Preheat oven to 350 degrees F (175 degrees C). Grease and flour three 8-inch round cake pans.",
            "In a medium bowl, whisk together flour, baking soda, and salt.",
            "In a large bowl, cream together butter and sugar until light and fluffy. Beat in eggs one at a time, then stir in vanilla extract.",
            "In a separate small bowl, whisk together buttermilk, cocoa powder, and red food coloring.",
            "Alternately add the dry ingredients and buttermilk mixture to the wet ingredients, beginning and ending with the dry ingredients. Mix until just combined.",
            "In a small bowl, combine white vinegar and baking soda. The mixture will fizz. Quickly stir it into the cake batter.",
            "Divide the batter evenly between the prepared pans. Bake for 25-30 minutes, or until a toothpick inserted into the center comes out clean.",
            "Let the cakes cool in the pans for 10 minutes, then transfer them to a wire rack to cool completely.",
            "In a large bowl, cream together cream cheese and butter until light and fluffy. Beat in powdered sugar one cup at a time, until smooth and creamy. Stir in vanilla extract.",
        ]
    ),
    new Recipe(
        "10",
        "Rich Coffee Mocha",
        "https://i.pinimg.com/564x/7a/64/e9/7a64e96f2f367e0d9421c8d445c0a4ce.jpg", // Update with the actual image URL
        "30 mins",
        "45 mins",
        "5",
        [
            // Cake ingredients
            "1 ¾ cups all-purpose flour",
            "1 teaspoon baking soda",
            "½ teaspoon salt",
            "1 cup (2 sticks) unsalted butter, softened",
            "1 ½ cups granulated sugar",
            "2 large eggs",
            "1 teaspoon pure vanilla extract",
            "1 cup buttermilk",
            "1 tablespoon cocoa powder",
            "1 tablespoon red food coloring",
            "1 tablespoon white vinegar",
            "8 oz cream cheese, softened",
            "½ cup unsalted butter, softened",
            "3 cups powdered sugar",
            "1 teaspoon pure vanilla extract",
        ],
        [
            "Preheat oven to 350 degrees F (175 degrees C). Grease and flour three 8-inch round cake pans.",
            "In a medium bowl, whisk together flour, baking soda, and salt.",
            "In a large bowl, cream together butter and sugar until light and fluffy. Beat in eggs one at a time, then stir in vanilla extract.",
            "In a separate small bowl, whisk together buttermilk, cocoa powder, and red food coloring.",
            "Alternately add the dry ingredients and buttermilk mixture to the wet ingredients, beginning and ending with the dry ingredients. Mix until just combined.",
            "In a small bowl, combine white vinegar and baking soda. The mixture will fizz. Quickly stir it into the cake batter.",
            "Divide the batter evenly between the prepared pans. Bake for 25-30 minutes, or until a toothpick inserted into the center comes out clean.",
            "Let the cakes cool in the pans for 10 minutes, then transfer them to a wire rack to cool completely.",
            "In a large bowl, cream together cream cheese and butter until light and fluffy. Beat in powdered sugar one cup at a time, until smooth and creamy. Stir in vanilla extract.",
        ]
    ),
    new Recipe(
        "11",
        "Earl Grey Lavender",
        "https://i.pinimg.com/564x/33/8a/41/338a41d91065b4d3eb727e72b98431fe.jpg", // Update with the actual image URL
        "30 mins",
        "45 mins",
        "5",
        [
            // Cake ingredients
            "1 ¾ cups all-purpose flour",
            "1 teaspoon baking soda",
            "½ teaspoon salt",
            "1 cup (2 sticks) unsalted butter, softened",
            "1 ½ cups granulated sugar",
            "2 large eggs",
            "1 teaspoon pure vanilla extract",
            "1 cup buttermilk",
            "1 tablespoon cocoa powder",
            "1 tablespoon red food coloring",
            "1 tablespoon white vinegar",
            "8 oz cream cheese, softened",
            "½ cup unsalted butter, softened",
            "3 cups powdered sugar",
            "1 teaspoon pure vanilla extract",
        ],
        [
            "Preheat oven to 350 degrees F (175 degrees C). Grease and flour three 8-inch round cake pans.",
            "In a medium bowl, whisk together flour, baking soda, and salt.",
            "In a large bowl, cream together butter and sugar until light and fluffy. Beat in eggs one at a time, then stir in vanilla extract.",
            "In a separate small bowl, whisk together buttermilk, cocoa powder, and red food coloring.",
            "Alternately add the dry ingredients and buttermilk mixture to the wet ingredients, beginning and ending with the dry ingredients. Mix until just combined.",
            "In a small bowl, combine white vinegar and baking soda. The mixture will fizz. Quickly stir it into the cake batter.",
            "Divide the batter evenly between the prepared pans. Bake for 25-30 minutes, or until a toothpick inserted into the center comes out clean.",
            "Let the cakes cool in the pans for 10 minutes, then transfer them to a wire rack to cool completely.",
            "In a large bowl, cream together cream cheese and butter until light and fluffy. Beat in powdered sugar one cup at a time, until smooth and creamy. Stir in vanilla extract.",
        ]
    ),
    new Recipe(
        "12",
        "Pistachio Rose Delight",
        "https://i.pinimg.com/564x/5f/10/70/5f1070d5e64d9070e22ec37b93692686.jpg", // Update with the actual image URL
        "30 mins",
        "45 mins",
        "5",
        [
            // Cake ingredients
            "1 ¾ cups all-purpose flour",
            "1 teaspoon baking soda",
            "½ teaspoon salt",
            "1 cup (2 sticks) unsalted butter, softened",
            "1 ½ cups granulated sugar",
            "2 large eggs",
            "1 teaspoon pure vanilla extract",
            "1 cup buttermilk",
            "1 tablespoon cocoa powder",
            "1 tablespoon red food coloring",
            "1 tablespoon white vinegar",
            "8 oz cream cheese, softened",
            "½ cup unsalted butter, softened",
            "3 cups powdered sugar",
            "1 teaspoon pure vanilla extract",
        ],
        [
            "Preheat oven to 350 degrees F (175 degrees C). Grease and flour three 8-inch round cake pans.",
            "In a medium bowl, whisk together flour, baking soda, and salt.",
            "In a large bowl, cream together butter and sugar until light and fluffy. Beat in eggs one at a time, then stir in vanilla extract.",
            "In a separate small bowl, whisk together buttermilk, cocoa powder, and red food coloring.",
            "Alternately add the dry ingredients and buttermilk mixture to the wet ingredients, beginning and ending with the dry ingredients. Mix until just combined.",
            "In a small bowl, combine white vinegar and baking soda. The mixture will fizz. Quickly stir it into the cake batter.",
            "Divide the batter evenly between the prepared pans. Bake for 25-30 minutes, or until a toothpick inserted into the center comes out clean.",
            "Let the cakes cool in the pans for 10 minutes, then transfer them to a wire rack to cool completely.",
            "In a large bowl, cream together cream cheese and butter until light and fluffy. Beat in powdered sugar one cup at a time, until smooth and creamy. Stir in vanilla extract.",
        ]
    ),
]

export default recipes;
